### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by ryanhz** [fgnass/tamper#2]
When I use tamper to wrap a response from another server:

exports.wrap = tamper(function(req, res) {

```
// Return a function in order to capture and modify the response body: 
return function(body) {
    var result = (body.indexOf('resultCode')<0)? ('{"result":{"resultCode":1,"message":"success"},"results":'+body+'}') : body;
    return result;
}
```

});

I got gibberish in body, any suggestion?

**Comment by jami** [comment]
Moin

Same problem here. I have a backend that delivers a gzib compressed body. Looks like content-encoding isn't checked

**Comment by ryanhz** [comment]
Yes, it is the gzib compressed body issue, I finally use it only in the same server, only place it in the router middleware, and it work fine.

**Comment by hadynz** [comment]
> Yes, it is the gzib compressed body issue, **I finally use it only in the same server**, only place it in the router middleware, and it work fine.

I am getting the same issue as pointed out by @huzhiren, and wasn't clear what the final workaround to this problem.

The body content seems to be compressed. Is there a way to use something like `zlib` to inflate and then processes it? Or is there a way to disable compression altogether in express (for those who are using this in non-production environments)?

**Comment by hadynz** [comment]
An update - solution is to make sure your express instance is not running with compression.
